[build]
  publish = "dist/client"
  command = "npm install --include=dev && npx vite build"

[[redirects]]
  from = "/admin/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/admin/history"
  to = "/history.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
