// ========== CENTRALIZED CONFIGURATION ==========
// All magic numbers and tunable constants in one place.

export const SCORING = {
  /** Points awarded for a correct answer (mcq, true/false, freetext, slider, ordering) */
  CORRECT_POINTS: 3,
  /** Points awarded per correct choice in a multi-select question */
  MULTI_POINTS_PER_CORRECT: 1,
  /** Achievement thresholds (adjusted for simplified scoring) */
  ACHIEVEMENT_GOOD_SCORE: 15,
  ACHIEVEMENT_EXPERT_SCORE: 30,
} as const;

export const TIMERS = {
  GAME_START_COUNTDOWN_MS: 3000,
  TICK_INTERVAL_MS: 1000,
  TRAINING_LEADERBOARD_DELAY_MS: 2000,
  TRAINING_NEXT_QUESTION_DELAY_MS: 5000,
  TRAINING_CLEANUP_MS: 60_000,
  KEEP_ALIVE_INTERVAL_MS: 14 * 60 * 1000,
} as const;

export const RATE_LIMITS = {
  HTTP_WINDOW_MS: 60_000,
  HTTP_MAX_REQUESTS: 60,
  SOCKET_ANSWER: { max: 5, windowMs: 10_000 },
  SOCKET_REACT: { max: 10, windowMs: 10_000 },
  SOCKET_JOIN: { max: 5, windowMs: 30_000 },
  SOCKET_DEFAULT: { max: 20, windowMs: 10_000 },
} as const;

export const LIMITS = {
  MAX_QUESTIONS: 50,
  MAX_CHOICES: 8,
  MAX_ITEMS: 10,
  MAX_ACCEPTED_ANSWERS: 20,
  MAX_TITLE_LENGTH: 100,
  MAX_QUESTION_TEXT_LENGTH: 300,
  MAX_CHOICE_LENGTH: 150,
  MAX_EXPLANATION_LENGTH: 500,
  MAX_NICKNAME_LENGTH: 20,
  MAX_ROOMS: 100,
  MIN_TIMELIMIT: 5,
  MAX_TIMELIMIT: 120,
  DEFAULT_TIMELIMIT: 20,
  MAX_UNIT_LENGTH: 20,
  MAX_SANITIZE_LENGTH: 500,
  MAX_URL_LENGTH: 2000,
  MAX_HTTP_BUFFER: 1e6,
  MAX_JSON_BODY: '1mb',
  MIN_PIN_LENGTH: 6,
  PIN_RANGE_MIN: 100000,
  PIN_RANGE_MAX: 900000,
} as const;

export const REDIS = {
  QUIZ_TTL: 86400,
  ROOM_SNAPSHOT_TTL: 3600,
} as const;

export const DB = {
  DEFAULT_QUIZ_LIST_LIMIT: 50,
  DEFAULT_HISTORY_LIMIT: 50,
  DEFAULT_LEADERBOARD_LIMIT: 50,
  MAX_LEADERBOARD_LIMIT: 100,
  QUERY_SCAN_LIMIT: 200,
  WEEK_MS: 7 * 24 * 60 * 60 * 1000,
  MONTH_MS: 30 * 24 * 60 * 60 * 1000,
} as const;

export const ROOM_GC = {
  ROOM_TTL_MS: 2 * 60 * 60 * 1000,
  GC_INTERVAL_MS: 10 * 60 * 1000,
} as const;

// Client-side constants (also exported for shared use)
export const CLIENT = {
  LOADING_SLOW_THRESHOLD_S: 3,
  KICKED_RELOAD_DELAY_MS: 3000,
  COUNTDOWN_VIBRATE_INITIAL: 200,
  COUNTDOWN_VIBRATE_TICK: 100,
  ANSWER_TRANSITION_DELAY_MS: 500,
  ANSWER_VIBRATE_TAP: 30,
  ANSWER_VIBRATE_CORRECT: 100,
  ANSWER_VIBRATE_WRONG: [50, 50, 50] as readonly number[],
  RESULT_REVEAL_DELAY_MS: 1500,
  REACTION_LIFETIME_MS: 2000,
  PODIUM_DELAYS_MS: [500, 2500, 5000] as readonly number[],
  ACHIEVEMENT_BASE_DURATION_MS: 4500,
  ACHIEVEMENT_STAGGER_MS: 600,
  LEADERBOARD_ROW_DELAY_S: 0.08,
  FINAL_LEADERBOARD_ROW_DELAY_S: 0.06,
  FINAL_LEADERBOARD_MAX_ROWS: 10,
} as const;

export const CONFETTI = {
  PARTICLE_COUNT: 150,
  MAX_FRAMES: 300,
  GRAVITY: 0.05,
  FADE_START_FRAMES_FROM_END: 60,
  OPACITY_DECREMENT: 0.02,
} as const;

export const AUDIO = {
  LOBBY_GAIN: 0.08,
  LOBBY_NOTE_INTERVAL_MS: 400,
  TENSION_BASE_GAIN: 0.06,
  TENSION_BASE_FREQ: 110,
  TENSION_BASE_BPM: 90,
  TENSION_MAX_BPM_DELTA: 90,
} as const;
