// ========== CLIENT-SIDE CONFIGURATION ==========
// Mirrors relevant constants from lib/config.ts for the browser.

export const TIMING = {
  LOADING_SLOW_THRESHOLD_S: 3,
  LOADING_CHECK_INTERVAL_MS: 1000,
  KICKED_RELOAD_DELAY_MS: 3000,
  ANSWER_TRANSITION_MS: 500,
  RESULT_REVEAL_MS: 1500,
  REACTION_LIFETIME_MS: 2000,
  ACHIEVEMENT_BASE_DURATION_MS: 4500,
  ACHIEVEMENT_STAGGER_MS: 600,
};

export const VIBRATION = {
  COUNTDOWN_INITIAL: 200,
  COUNTDOWN_TICK: 100,
  ANSWER_TAP: 30,
  CORRECT: 100,
  WRONG: [50, 50, 50],
};

export const PODIUM = {
  DELAYS_MS: [500, 2500, 5000],
};

export const ANIMATION = {
  LEADERBOARD_ROW_DELAY_S: 0.08,
  FINAL_ROW_DELAY_S: 0.06,
  FINAL_MAX_ROWS: 10,
};

export const VALIDATION = {
  MIN_PIN_LENGTH: 6,
};

export const CONFETTI = {
  PARTICLE_COUNT: 150,
  MAX_FRAMES: 300,
  GRAVITY: 0.05,
  FADE_START_FRAMES_FROM_END: 60,
  OPACITY_DECREMENT: 0.02,
};

export const AUDIO = {
  LOBBY_GAIN: 0.08,
  LOBBY_NOTE_INTERVAL_MS: 400,
  TENSION_BASE_GAIN: 0.06,
  TENSION_BASE_FREQ: 110,
  TENSION_BASE_BPM: 90,
  TENSION_MAX_BPM_DELTA: 90,
};
